---
- hosts: dns
  gather_facts: false

  tasks:
  - name: Disable systemd-resolved service
    systemd:
      name: systemd-resolved
      enabled: no
      state: stopped
    become: true

  - name: Install Bind dependencies
    apt: name={{item}} state=present
    with_items:
      - software-properties-common
      - python-software-properties
      - ca-certificates
      - apt-transport-https
      - bind9
      - bind9-doc
      - bind9-host
      - bind9utils
    become: true

  - name: Download named.conf.default-zones
    get_url:
      url: https://s3-us-west-1.amazonaws.com/s3-k8s-bind/named.conf.default-zones
      dest: /etc/bind
      mode: 0644
    become: true

  - name: Download named.conf.options
    get_url:
      url: https://s3-us-west-1.amazonaws.com/s3-k8s-bind/named.conf.options
      dest: /etc/bind
      mode: 0644
    become: true

  - name: Download db.192.0
    get_url:
      url: https://s3-us-west-1.amazonaws.com/s3-k8s-bind/db.192.0
      dest: /etc/bind
      mode: 0644
    become: true

  - name: Download db.192.1
    get_url:
      url: https://s3-us-west-1.amazonaws.com/s3-k8s-bind/db.192.1
      dest: /etc/bind
      mode: 0644
    become: true

  - name: Download db.192.2
    get_url:
      url: https://s3-us-west-1.amazonaws.com/s3-k8s-bind/db.192.2
      dest: /etc/bind
      mode: 0644
    become: true

  - name: Download db.lab
    get_url:
      url: https://s3-us-west-1.amazonaws.com/s3-k8s-bind/db.lab
      dest: /etc/bind
      mode: 0644
    become: true

  - name: Restart bind9 service
    service:
      name: bind9
      enabled: yes
      state: restarted
    become: true