vcenter: "vcenter.home.virtualelephant.com"
vcenter_user: "administrator@vsphere.local"
vcenter_pass: ""
dc: "Datacenter"
ubuntu_template: "Ubuntu-18.04LTS-Template"
cluster_name: "R640 Cluster"
datastore: "syn-lun4"

folder: "Kubernetes"
vm_prefix: "cilium"
description: "created through Ansible playbook"

num_nodes: 6

dns1_ip: "10.1.10.2"
master1_ip: "10.1.105.5"
master2_ip: "10.1.105.6"
master3_ip: "10.1.105.7"
nameserver_ips: "[10.1.10.2,8.8.8.8]"
netmask: "255.255.255.0"
gateway: "10.1.105.1"
