---
- hosts: kube-cluster
  gather_facts: false
  become: yes

  vars:
    join_command_location: "{{ home_dir }}/git/vsphere-kubernetes/ansible/files/cluster_join.out"

  vars_files:
    - envanswer.yml

  tasks:

  - block:
  # Currently only leveraging 1 of 3 controllers
      - name: Initialize Kubernetes cluster
        command: "kubeadm init --pod-network-cidr {{ pod_cidr }}"
        register: kube_init

      - name: Extract the cluster join command
        command: "kubeadm token create --print-join-command"
        register: join_command

      - name: Create .kube directory
        file:
          path: "{{ home_dir }}/.kube"
          state: directory
          owner: 1000
          group: 1000

      - name: Configure .kube/config files
        copy:
          src: /etc/kubernetes/admin.conf
          dest: "{{ home_dir }}/.kube/config"
          remote_src: yes
          owner: 1000
          group: 1000

      - pause:
          minutes: 1

      - name: Install Flannel CNI
        raw: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
        become: no
        register: flannel_init

      - name: Save kubeadm join command for cluster
        local_action: copy content={{ join_command.stdout_lines | last | trim }} dest={{ join_command_location }}

      - pause:
          minutes: 5

      - name: Copy join command to minion nodes
        copy:
          src: "{{ join_command_location }}"
          dest: "{{ home_dir }}/"
          owner: 1000
          group: 1000
          mode: '0644'

    when: "'controller1' in inventory_hostname"

  - name: Read join command on minion nodes
    debug: msg={{ lookup('file', join_command_location) }}
    register: join_command_local
    when: "'node' in inventory_hostname"

  - name: Join minions to Kubernetes cluster
    command: "{{ join_command_local.msg }}"
    when: "'node' in inventory_hostname"
      
