---
- hosts: cilium-controllers
  gather_facts: false
  become: yes

  vars_files:
    - envanswer.yml

  tasks:
  - name: Download the Helm v3 release
    get_url:
      url: https://get.helm.sh/helm-v3.2.0-linux-amd64.tar.gz
      dest: "{{ home_dir }}/helm-v3.2.0-linux-amd64.tar.gz"
      mode: '0644'
      
  - name: Untar the Helm v3 release
    unarchive:
      src: helm-v3.2.0-linux-amd64.tar.gz
      dest: "{{ home_dir }}"
      remote_src: yes

  - name: Copy helm binary
    shell: "mv {{ home_dir }}/linux-amd64/helm /usr/local/bin"

  - name: Add Kubernetes Helm Charts repo
    shell: "helm repo add stable https://kubernetes-charts.storage.googleapis.com/"

  - name: Update Helm repos
    shell: "helm repo update"

  - block:
      - name: Clone Hubble GitHub repo
        shell: "git clone https://github.com/cilium/hubble.git"

      - name: Copy Hubble command to controller
        copy:
          src: files/hubble.cmd
          dest: "{{ home_dir }}/hubble/install/kubernetes"
          mode: '0755'

      - name: Create Hubble YAML file for Kubernetes
        shell: "{{ home_dir }}/hubble/install/kubernetes/hubble.cmd"
        args:
          chdir: "{{ home_dir }}/hubble/install/kubernetes"
    when: "'controller1' in inventory_hostname"

- hosts: cilium-cluster
  gather_facts: false
  become: yes

  vars_files:
    - envanswer.yml

  tasks:
  - name: Create UNIX file socket for Hubble
    file:
      path: /var/run/hubble.sock
      state: touch
      owner: root
      group: root
      mode: '0664'

- hosts: cilium-controllers
  gather_facts: false
  become: yes

  vars_files:
    - envanswer.yml

  tasks:
  - block:
      - name: Copy modified hubble.yaml file to controller1
        copy:
          src: files/hubble.yaml
          dest: "{{ home_dir }}/hubble/install/kubernetes"
          mode: '0644'
          force: yes
          backup: yes

      - name: Initialize Hubble in the kube-system namespace
        raw: "kubectl apply -f {{ home_dir }}/hubble/install/kubernetes/hubble.yaml"
        become: no

      - pause:
          minutes: 5

      - name: Copy Grafana & Prometheus YAML file for Hubble
        copy:
          src: files/monitoring-example.yaml
          dest: "{{ home_dir }}"
          mode: "0644"

      - name: Create cilium-monitoring namespace
        raw: "kubectl create namespace cilium-monitoring"
        become: no

      - name: Initialize cilium-monitoring pod
        raw: "kubectl apply -f {{ home_dir }}/monitoring-example.yaml"
        become: no
  
    when: "'controller1' in inventory_hostname"

