---
# installation.yml
# Install Kubernetes on Ubuntu VMs
# Base Kubernetes package installation
- import_playbook: update-os.yml
- import_playbook: kubernetes-install.yml
- import_playbook: kubernetes-config.yml
