---
- hosts: localhost
  gather_facts: false
  connection: local

  vars_files:
    - envanswer.yml

  tasks:
  - name: Create 1st Ubuntu Kubernetes master VM
    vmware_guest:
      hostname: "{{ vcenter }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_pass }}"
      validate_certs: False
      name: "{{ vm_prefix }}-master-1"
      template: "{{ ubuntu_template }}"
      datacenter: "{{ dc }}"
      cluster: "{{ cluster_name }}"
      folder: "{{ folder }}"
      state: poweredoff
    delegate_to: localhost
    register: createvm

  - name: Create 2nd Ubuntu Kubernetes master VM
    vmware_guest:
      hostname: "{{ vcenter }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_pass }}"
      validate_certs: False
      name: "{{ vm_prefix }}-master-2"
      template: "{{ ubuntu_template }}"
      datacenter: "{{ dc }}"
      cluster: "{{ cluster_name }}"
      folder: "{{ folder }}"
      state: poweredoff
    delegate_to: localhost
    register: createvm

  - name: Create 3rd Ubuntu Kubernetes master VM
    vmware_guest:
      hostname: "{{ vcenter }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_pass }}"
      validate_certs: False
      name: "{{ vm_prefix }}-master-3"
      template: "{{ ubuntu_template }}"
      datacenter: "{{ dc }}"
      cluster: "{{ cluster_name }}"
      folder: "{{ folder }}"
      state: poweredoff
    delegate_to: localhost
    register: createvm
