---
- hosts: localhost
  gather_facts: false
  connection: local

  vars_files:
    - envanswer.yml

  tasks:
  - name: Create Minion VMs from Ubuntu template
    vmware_guest:
      hostname: "{{ vcenter }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_pass }}"
      validate_certs: False
      name: "{{ vm_prefix }}-node0{{ item }}"
      template: "{{ ubuntu_template }}"
      datacenter: "{{ dc }}"
      cluster: "{{ cluster_name }}"
      state: poweredoff
      folder: "/vm/{{ folder }}"
    delegate_to: localhost
    register: createvm
    with_sequence: start=1 end={{num_nodes|int}}
