---
- hosts: localhost
  gather_facts: false
  connection: local

  vars_files:
    - envanswer.yml

  tasks:
  - name: Check for existing VM folder
    vmware_folder:
      hostname: "{{ vcenter }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_pass }}"
      validate_certs: False
      datacenter: "{{ dc }}"
      cluster: "{{ cluster_name }}"
      folder: "{{ folder }}"
      state: present

  - name: Gather MOID for NSX Logical Switch Portgroup
    vcenter_gather_moids:
      hostname: "{{ vcenter }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_pass }}"
      datacenter_name: "{{ dc }}"
      portgroup_name: "{{ switch_name }}"
      validate_certs: False
    register: gather_moids_pg

  - name: Create Minion VMs from blank CoreOS template
    vmware_guest:
      hostname: "{{ vcenter }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_pass }}"
      validate_certs: False
      name: "{{ vm_prefix }}-node-coreos{{ item }}"
      template: "{{ coreos_template }}"
      datacenter: "{{ dc }}"
      cluster: "{{ cluster_name }}"
      networks:
      - name: " {{ gather_moids_pg.object_name }}"
      state: poweredon
      folder: "/vm/{{ folder }}"
    delegate_to: localhost
    register: createvm
    with_sequence: start=1 end={{num_nodes|int}}
