---
# main.yml
# Deploy and configure a complete Kubernetes stack within a VMware vSphere
# environment that includes VMware NSX.
#
# Future: Add creation of required templates.

- import_playbook: kube-master-deploy.yml
- import_playbook: kube-nodes-deploy.yml
- import_playbook: kube-drs-rules.yml
- import_playbook: vm-config-nics.yml
