---
- hosts: cilium-cluster
  gather_facts: false
  become: yes

  vars_files:
    - envanswer.yml

  tasks:
  - name: Install NFS-client support
    apt:
      name: ['nfs-common']
      force_apt_get: yes
      state: present

  - name: Persistent volume mount for Grafana
    mount:
      path: /opt/grafana
      src: 10.1.10.15:/opt/persistent/grafana
      fstype: nfs
      opts: rw,auto,nofail,noatime
      state: mounted

  - name: Persistent volume mount for Prometheus
    mount:
      path: /opt/prometheus
      src: 10.1.10.15:/opt/persistent/prometheus
      fstype: nfs
      opts: rw,auto,nofail,noatime
      state: mounted

