---
- hosts: localhost
  connection: local
  gather_facts: False
  vars_files:
    - nsxanswer.yml
    - envanswer.yml

  tasks:
  - name: Create DHCP pool on NSX Edge
    nsx_edge_dhcp:
      nsxmanager_spec: "{{ nsxmanager_spec }}"
      name: '{{ edge_name }}'
      mode: 'create_pool'
      ip_range: '{{ ip_range }}'
      subnet: '{{ netmask }}'
      default_gateway: '{{ gateway }}'
      domain_name: '{{ domain }}'
      dns_server_1: '{{ dns1_ip }}'
      dns_server_2: '{{ dns2_ip }}'
      lease_time: '{{ lease_time }}'
      next_server: '{{ tftp_server }}'
      bootfile: '{{ bootfile }}'
