---
- hosts: localhost
  connection: local
  gather_facts: False
  vars_files:
    - nsxanswer.yml
    - envanswer.yml

  tasks:
  - name: Create SSH Bastion host DNAT rule
    nsx_edge_nat:
      nsxmanager_spec: '{{ nsxmanager_spec }}'
      mode: 'create'
      name: '{{ edge_name }}'
      description: 'Ansible created inbound SSH'
      loggingEnabled: 'true'
      rule_type: 'dnat'
      vnic: '0'
      protocol: 'tcp'
      originalAddress: '10.180.138.131'
      originalPort: '22'
      translatedAddress: '192.168.0.2'
      translatedPort: '22'

  - name: Create default outbound SNAT rule
    nsx_edge_nat:
      nsxmanager_spec: '{{ nsxmanager_spec }}'
      mode: 'create'
      name: '{{ edge_name }}'
      description: 'Ansible created default outbound'
      loggingEnabled: 'true'
      rule_type: 'snat'
      vnic: '0'
      protocol: 'any'
      originalAddress: '192.168.0.0/20'
      originalPort: 'any'
      translatedAddress: '10.180.138.131'
      translatedPort: 'any'
